---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tabulizer)
url <- "https://www.cbp.gov/sites/default/files/assets/documents/2017-Dec/BP%20Southwest%20Border%20Sector%20Apps%20FY1960%20-%20FY2017.pdf"


```



```{r}
data <- url %>% 
  extract_tables()

data %>% unlist() %>% class()


as.data.frame(data[1:nrow(data), ])
```


```{r}
df <- read_csv("tabula-CBP_data.csv") 

df



coord <- read_csv("CBP_coordinates.csv")

coord
```

```{r}
df2 <- df %>% 
  gather(Region,Number,2:11) %>% 
  # mutate_at(vars(`Fiscal\rYear`),as.factor) %>% 
  mutate(Region = as.factor(Region))

df2
```


```{r}
df2 %>% 
  inner_join(coord)




us <- map_data("state")
us
```



```{r}
df2 %>% ggplot(aes(x = `Fiscal Year`, y = Number/1E5, color = Region, group = Region)) +
  geom_rect(aes(xmin = 2009, xmax = 2016, ymin=0, ymax = 5), fill = "skyblue", alpha = 0.6) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(1960,2020,5)) 

```

```{r}

us %>% 
ggplot() + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE)
```

